name: malik
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2" # add this line

flutter_icons:    # add this section
  android: "launcher_icon"
  ios: true
  image_path: "assets/picon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
